export const ACTION_NAMES = {
    // HOME
    FETCH_HOME_PAGE_DATA: 'FETCH.HOMEPAGE.DATA',
    SET_HOME_PAGE_DATA: 'SET.HOMEPAGE.DATA',
    CLEAR_HOME_PAGE_DATA: 'CLEAR.HOMEPAGE.DATA',
    // ABOUTME
    FETCH_ABOUT_ME_PAGE_DATA: 'FETCH.ABOUTMEPAGE.DATA',
    SET_ABOUT_ME_PAGE_DATA: 'SET.ABOUTMEPAGE.DATA',
    CLEAR_ABOUT_ME_PAGE_DATA: 'CLEAR.ABOUTMEPAGE.DATA',
    // CERTIFICATES
    FETCH_CERTIFICATES_PAGE_DATA: 'FETCH.CERTIFICATESPAGE.DATA',
    SET_CERTIFICATES_PAGE_DATA: 'SET.CERTIFICATESPAGE.DATA',
    CLEAR_CERTIFICATES_PAGE_DATA: 'CLEAR.CERTIFICATESPAGE.DATA',
    // EXPERIENCE
    FETCH_EXPERIENCE_PAGE_DATA: 'FETCH.EXPERIENCEPAGE.DATA',
    SET_EXPERIENCE_PAGE_DATA: 'SET.EXPERIENCEPAGE.DATA',
    CLEAR_EXPERIENCE_PAGE_DATA: 'CLEAR.EXPERIENCEPAGE.DATA',
    // SKILLS
    FETCH_SKILLS_PAGE_DATA: 'FETCH.SKILLSPAGE.DATA',
    SET_SKILLS_PAGE_DATA: 'SET.SKILLSPAGE.DATA',
    CLEAR_SKILLS_PAGE_DATA: 'CLEAR.SKILLSPAGE.DATA',
};
